### ISSUE TITLE
Crash in "wf source list" if first source is nil

### ISSUE THREAD

**Issue by elfchief** [snltd/wavefront-cli#7]
When doing a "wf source list" on my wavefront accounts, I get an error: `general error: undefined method 'size' for nil:NilClass`. When rerun with -D, the following is generated (slightly sanitized):

```$ wf source list -L 1 -D
{:endpoint=>"xxxx.wavefront.com",
 :format=>"human",
 :token=>"x",
 :source=>true,
 :list=>true,
 :debug=>true,
 :noop=>false,
 :verbose=>false,
 :long=>false,
 :limit=>"1",
 :all=>false,
 :describe=>false,
 :description=>false,
 :set=>false,
 :clear=>false,
 :search=>false,
 :"<condition>"=>[],
 :tags=>false,
 :tag=>false,
 :"<tag>"=>[],
 :add=>false,
 :delete=>false,
 :help=>false}
#<Faraday::Response:0x007fbdfeace590
 @env=
  #<struct Faraday::Env
   method=:get,
   body=
    "{\"status\":{\"result\":\"OK\",\"message\":\"\",\"code\":200},\"response\":{\"items\":[{\"id\":\"(none)\",\"hidden\":false,\"sourceName\":\"(none)\"}],\"limit\":1,\"cursor\":\"(none)\",\"moreItems\":true}}",
   url=#<URI::HTTPS https://xxx.wavefront.com/api/v2/source?limit=1>,
   request=
    #<struct Faraday::RequestOptions
     params_encoder=nil,
     proxy=nil,
     bind=nil,
     timeout=nil,
     open_timeout=nil,
     boundary=nil,
     oauth=nil,
     context=nil>,
   request_headers=
    {"Authorization"=>"Bearer x",
     "User-agent"=>"wavefront-cli-1.0.2"},
   ssl=
    #<struct Faraday::SSLOptions
     verify=true,
     ca_file=nil,
     ca_path=nil,
     verify_mode=nil,
     cert_store=nil,
     client_cert=nil,
     client_key=nil,
     certificate=nil,
     private_key=nil,
     verify_depth=nil,
     version=nil>,
   parallel_manager=nil,
   params=nil,
   response=#<Faraday::Response:0x007fbdfeace590 ...>,
   response_headers=
    {"server"=>"nginx",
     "date"=>"Tue, 22 Aug 2017 20:07:28 GMT",
     "content-type"=>"application/json",
     "content-length"=>"171",
     "connection"=>"close",
     "x-upstream"=>"10.1.0.137:34136",
     "x-wavefront-cluster"=>"/services-us-west-2c",
     "x-frame-options"=>"SAMEORIGIN"},
   status=200,
   reason_phrase="OK">,
 @on_complete_callbacks=[]>
#<Wavefront::Response:0x007fbdfe962e40 @status=#<Wavefront::Type::Status:0x007fbdfe962530 @message="", @code=200, @result="OK">, @response={"items"=>[{"id"=>"(none)", "hidden"=>false, "sourceName"=>"(none)"}],
 "limit"=>1,
 "cursor"=>"(none)",
 "moreItems"=>true}
>
general error: undefined method `size' for nil:NilClass
Backtrace:
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/printer/terse.rb:37:in `block (2 levels) in longest_keys'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/printer/terse.rb:34:in `each'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/printer/terse.rb:34:in `block in longest_keys'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/printer/terse.rb:32:in `each'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/printer/terse.rb:32:in `each_with_object'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/printer/terse.rb:32:in `longest_keys'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/printer/terse.rb:22:in `format_string'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/printer/terse.rb:15:in `initialize'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/base.rb:106:in `new'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/base.rb:106:in `multicolumn'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/source.rb:15:in `do_list_brief'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/base.rb:52:in `run_list'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/display/base.rb:33:in `run'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/base.rb:214:in `handle_response'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/base.rb:189:in `display'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/base.rb:147:in `block in dispatch'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/base.rb:144:in `each'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/base.rb:144:in `dispatch'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/base.rb:45:in `run'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/controller.rb:86:in `run_command'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/lib/wavefront-cli/controller.rb:29:in `initialize'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/bin/wf:18:in `new'
	/usr/local/lib/ruby/gems/2.4.0/gems/wavefront-cli-1.0.2/bin/wf:18:in `<top (required)>'
	/usr/local/bin/wf:22:in `load'
	/usr/local/bin/wf:22:in `<main>'
```

I'm pretty sure the problem is because our first source (which shows up in the wavefront interface as `(none)`) seems to be completely invalid. I'm seeing this in at least two different wavefront instances, though, so it seems like something wavefront-cli should be able to handle.

As a temporary workaround, I updated longest_keys to look like this:

```
    def longest_keys
      keys.each_with_object(Hash[*keys.map { |k| [k, 0] }.flatten]) \
      do |k, aggr|
        data.each do |obj|
          val = obj[k]
+          next if val.nil?
          val = val.join(', ') if val.is_a?(Array)
          aggr[k] = val.size if val.size > aggr[k]
        end
      end
    end
```

...and that works (giving the first source as `(none)`). I'm not submitting it as a pull request because I'm not sure this is a good fix, and not sure if there are other things that would need to be changed to properly accomodate this.

**Comment by snltd** [comment]
Thanks a lot for the report.

I think the issue comes from trying to find the maximum length of a property which sources do not possess. For me, it blew up trying to find the longest `obj[:description]` on a source which has no description. So, your fix was the right one, but I've implemented it in a slightly more explicit way.

The bug is fixed in version 1.0.3 of the gem.
